name: Auto Close Issues & PRs Between 10PM–12AM (Kolkata)

on:
  schedule:
    # Runs every 10 minutes between 16:30–18:30 UTC on Oct 31 (10PM–12AM IST)
    - cron: '*/10 16-18 31 10 *'
    - cron: '0,10,20,30 18 31 10 *'  # Covers 18:00, 18:10, 18:20, 18:30 UTC
  workflow_dispatch:

jobs:
  close-night-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issues and PRs opened between 10PM–12AM IST
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const now = new Date();
            console.log("Current UTC time:", now.toISOString());

            // Utility: check if a creation time falls within 10PM–12AM IST (16:30–18:30 UTC)
            function isWithinEventWindow(createdAt) {
              const utcHour = createdAt.getUTCHours();
              const utcMinute = createdAt.getUTCMinutes();
              const totalUTCMinutes = utcHour * 60 + utcMinute;
              // 16:30 (990 min) <= created < 18:30 (1110 min)
              return totalUTCMinutes >= 990 && totalUTCMinutes < 1110;
            }

            // === Handle Issues ===
            const { data: issues } = await github.rest.issues.listForRepo({
              ...context.repo,
              state: "open",
              per_page: 100
            });

            if (issues.length === 0) {
              console.log("✅ No open issues or PRs to close right now.");
            } else {
              for (const issue of issues) {
                const createdAt = new Date(issue.created_at);

                if (isWithinEventWindow(createdAt)) {
                  if (issue.pull_request) {
                    // It's a PR
                    await github.rest.issues.createComment({
                      ...context.repo,
                      issue_number: issue.number,
                      body: "🚫 Pull Requests cannot be opened or kept open between **10 PM and 12 AM (Kolkata time)** on 31 Oct 2025 due to event rules."
                    });
                    await github.rest.pulls.update({
                      ...context.repo,
                      pull_number: issue.number,
                      state: "closed"
                    });
                    console.log(`Closed PR #${issue.number} (created at ${createdAt.toISOString()})`);
                  } else {
                    // It's an Issue
                    await github.rest.issues.createComment({
                      ...context.repo,
                      issue_number: issue.number,
                      body: "🚫 Issues cannot be created or kept open between **10 PM and 12 AM (Kolkata time)** on 31 Oct 2025 due to event rules."
                    });
                    await github.rest.issues.update({
                      ...context.repo,
                      issue_number: issue.number,
                      state: "closed"
                    });
                    console.log(`Closed issue #${issue.number} (created at ${createdAt.toISOString()})`);
                  }
                }
              }
            }

            console.log("✅ Auto-close check completed.");
