name: Mark stale issues and PRs

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:       # Allows manual run

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as **stale** because it hasn’t had any activity in 5 days. Please comment or remove the stale label if this is still relevant."
          stale-pr-message: "This pull request has been automatically marked as **stale** because it hasn’t had any activity in 5 days. Please comment or remove the stale label if this PR is still relevant."
          days-before-stale: 5
          days-before-close: 2
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "pinned,security,enhancement"
          exempt-pr-labels: "work-in-progress"
